export default {
  logo_title:require('../assets/images/title.png'),
  logo:require('../assets/images/logo.svg'),
  menuUser: require('../assets/images/menuUser.svg'),
  menuUserS: require('../assets/images/menuUserS.svg'),
  menuAdress: require('../assets/images/menuAdress.svg'),
  menuAdressS: require('../assets/images/menuAdressS.svg'),
  emojiFace: require('../assets/images/face.svg'),
  uploadPic: require('../assets/images/uploadPic.svg'),
  message:require('../assets/images/message.svg'),
  expression:require('../assets/images/expression.svg'),
  information:require('../assets/images/information.svg'),
  edit:require('../assets/images/edit.svg'),
  close:require('../assets/images/close.svg'),
  save:require('../assets/images/save.svg'),
  video:require('../assets/images/video.png'),
  listNull:require('../assets/images/listNull.svg'),
  avatar:require('../assets/images/avatar.svg'),
  warning:require('../assets/images/warning.svg'),
  groupAvatar:require('../assets/images/groupAvatar.svg'),
  personAvatar:require('../assets/images/personAvatar.svg'),
  sanjiao:require('../assets/images/sanjiao.svg'),
  noContent:require('../assets/images/noContent.svg'),
  link:require('../assets/images/link.svg'),
  redPackage:require('../assets/images/redPackage.svg'),
  transfer:require('../assets/images/transfer.svg'),
  redPackageOpen:require('../assets/images/redPackageOpen.png'),
  transferOpen:require('../assets/images/transferOpen.svg'),
  download:require('../assets/images/download.svg'),
  notFound:require('../assets/images/notFound.svg'),
  nothing:require('../assets/images/nothing.png'),
  scanner:require('../assets/images/scanner.png'),
  loadingMore:require('../assets/images/loadingMore.svg'),
  location:require('../assets/images/location.svg')
}
